In [41]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [42]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [43]:
print(x)

[['Vans' 40 79000]
 ['Converse' 39 91000]
 ['Adidas' 36 61000]
 ['Converse' 38 61000]
 ['Adidas' 39 85000]
 ['Vans' 37 70000]
 ['Converse' 41 92000]
 ['Vans' 42 75000]
 ['Adidas' 41 83000]
 ['France' 37 67000]]


In [44]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [45]:
from sklearn.impute import SimpleImputer
impute = SimpleImputer(missing_values=np.nan, strategy='mean')
impute.fit(x[:, 1:3])
x[:, 1:3] = impute.transform(x[:, 1:3])

In [46]:
print(x)

[['Vans' 40.0 79000.0]
 ['Converse' 39.0 91000.0]
 ['Adidas' 36.0 61000.0]
 ['Converse' 38.0 61000.0]
 ['Adidas' 39.0 85000.0]
 ['Vans' 37.0 70000.0]
 ['Converse' 41.0 92000.0]
 ['Vans' 42.0 75000.0]
 ['Adidas' 41.0 83000.0]
 ['France' 37.0 67000.0]]


In [47]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [48]:
print(x)

[[0.0 0.0 0.0 1.0 40.0 79000.0]
 [0.0 1.0 0.0 0.0 39.0 91000.0]
 [1.0 0.0 0.0 0.0 36.0 61000.0]
 [0.0 1.0 0.0 0.0 38.0 61000.0]
 [1.0 0.0 0.0 0.0 39.0 85000.0]
 [0.0 0.0 0.0 1.0 37.0 70000.0]
 [0.0 1.0 0.0 0.0 41.0 92000.0]
 [0.0 0.0 0.0 1.0 42.0 75000.0]
 [1.0 0.0 0.0 0.0 41.0 83000.0]
 [0.0 0.0 1.0 0.0 37.0 67000.0]]


In [49]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [50]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [51]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [52]:
print(x_train)

[[0.0 1.0 0.0 0.0 41.0 92000.0]
 [1.0 0.0 0.0 0.0 39.0 85000.0]
 [0.0 0.0 0.0 1.0 40.0 79000.0]
 [0.0 1.0 0.0 0.0 38.0 61000.0]
 [0.0 1.0 0.0 0.0 39.0 91000.0]
 [0.0 0.0 0.0 1.0 42.0 75000.0]
 [1.0 0.0 0.0 0.0 41.0 83000.0]
 [0.0 0.0 0.0 1.0 37.0 70000.0]]


In [53]:
print(x_test)

[[1.0 0.0 0.0 0.0 36.0 61000.0]
 [0.0 0.0 1.0 0.0 37.0 67000.0]]


In [54]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [55]:
print(y_test)

[0 1]


In [56]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [57]:
print(x_train)

[[0.0 1.0 0.0 -0.7745966692414834 0.8723567442899586 1.2626906806902634]
 [1.0 0.0 0.0 -0.7745966692414834 -0.3965257928590721 0.5555838995037159]
 [0.0 0.0 0.0 1.2909944487358056 0.23791547571544325 -0.05050762722761054]
 [0.0 1.0 0.0 -0.7745966692414834 -1.0309670614335873 -1.8687822074215898]
 [0.0 1.0 0.0 -0.7745966692414834 -0.3965257928590721 1.1616754262350424]
 [0.0 0.0 0.0 1.2909944487358056 1.5067980128644738 -0.45456864504849487]
 [1.0 0.0 0.0 -0.7745966692414834 0.8723567442899586 0.3535533905932738]
 [0.0 0.0 0.0 1.2909944487358056 -1.6654083300081026 -0.9596449173246002]]


In [58]:
print(x_test)

[[1.0 0.0 0.0 -0.7745966692414834 -2.2998495985826177 -1.8687822074215898]
 [0.0 0.0 1.0 -0.7745966692414834 -1.6654083300081026 -1.2626906806902634]]
